# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160504_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
