# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160505_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollChoices',
            new_name='PollChoice',
        ),
    ]
