# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone_validated',
            field=models.BooleanField(default=False),
        ),
    ]
