# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_voter_phone_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellCarriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sms_gateway', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voters.CellCarriers'),
            preserve_default=False,
        ),
    ]
