# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_auto_20160510_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CellCarriers',
            new_name='CellCarrier',
        ),
    ]
