# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_auto_20160510_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone_key',
            field=models.IntegerField(default=1111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='phone_key_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 10, 20, 24, 10, 386245, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
